import { Agent, AgentStatus, ClusterType, ClusterStats, Task, TaskStatus, Event, EventSeverity, Mission, MissionState, MissionPriority, CollaborationPattern, ClusterHealthInfo, UnifiedConnectorInfo, OrchestrationStatistics, OrchestrationHistoryItem, DecompositionResult, CoordinationResult, CollaborationResult } from './types';

export const mockAgents: Agent[] = [
  { id: '1', name: 'Navigation Agent', cluster: ClusterType.BROWSER, status: AgentStatus.RUNNING, config: {}, capabilities: ['navigate', 'interact'], tenantId: 't1', version: '1.0.0', description: 'Handles web navigation and page traversal', isEnabled: true, lastExecutionAt: '2026-03-10T10:30:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T10:30:00Z' },
  { id: '2', name: 'Scraping Agent', cluster: ClusterType.BROWSER, status: AgentStatus.IDLE, config: {}, capabilities: ['scrape', 'extract'], tenantId: 't1', version: '1.2.0', description: 'Web scraping and data extraction', isEnabled: true, lastExecutionAt: '2026-03-09T15:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-09T15:00:00Z' },
  { id: '3', name: 'Terminal Agent', cluster: ClusterType.COMPUTER, status: AgentStatus.RUNNING, config: {}, capabilities: ['execute', 'shell'], tenantId: 't1', version: '2.0.0', description: 'Terminal command execution', isEnabled: true, lastExecutionAt: '2026-03-10T12:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T12:00:00Z' },
  { id: '4', name: 'Process Agent', cluster: ClusterType.COMPUTER, status: AgentStatus.ERROR, config: {}, capabilities: ['monitor', 'kill'], tenantId: 't1', version: '1.1.0', description: 'Process monitoring and management', isEnabled: true, lastExecutionAt: '2026-03-10T08:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T08:00:00Z' },
  { id: '5', name: 'Code Generation Agent', cluster: ClusterType.CODING, status: AgentStatus.IDLE, config: {}, capabilities: ['generate', 'refactor'], tenantId: 't1', version: '1.5.0', description: 'AI-powered code generation', isEnabled: true, lastExecutionAt: '2026-03-10T09:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T09:00:00Z' },
  { id: '6', name: 'Code Review Agent', cluster: ClusterType.CODING, status: AgentStatus.RUNNING, config: {}, capabilities: ['review', 'lint'], tenantId: 't1', version: '1.3.0', description: 'Automated code review', isEnabled: true, lastExecutionAt: '2026-03-10T11:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T11:00:00Z' },
  { id: '7', name: 'Document Agent', cluster: ClusterType.OFFICE, status: AgentStatus.COMPLETED, config: {}, capabilities: ['create', 'edit'], tenantId: 't1', version: '1.0.0', description: 'Document creation and editing', isEnabled: true, lastExecutionAt: '2026-03-10T07:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T07:00:00Z' },
  { id: '8', name: 'Email Agent', cluster: ClusterType.OFFICE, status: AgentStatus.PAUSED, config: {}, capabilities: ['send', 'read'], tenantId: 't1', version: '1.1.0', description: 'Email management and automation', isEnabled: true, lastExecutionAt: '2026-03-09T18:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-09T18:00:00Z' },
  { id: '9', name: 'SEO Agent', cluster: ClusterType.MARKETING, status: AgentStatus.RUNNING, config: {}, capabilities: ['optimize', 'analyze'], tenantId: 't1', version: '1.0.0', description: 'SEO optimization and analysis', isEnabled: true, lastExecutionAt: '2026-03-10T10:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T10:00:00Z' },
  { id: '10', name: 'Threat Detection Agent', cluster: ClusterType.SECURITY, status: AgentStatus.RUNNING, config: {}, capabilities: ['detect', 'alert'], tenantId: 't1', version: '2.1.0', description: 'Real-time threat detection', isEnabled: true, lastExecutionAt: '2026-03-10T12:30:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T12:30:00Z' },
  { id: '11', name: 'Orchestration Agent', cluster: ClusterType.META_INTELLIGENCE, status: AgentStatus.RUNNING, config: {}, capabilities: ['orchestrate', 'coordinate'], tenantId: 't1', version: '1.0.0', description: 'Agent orchestration and coordination', isEnabled: true, lastExecutionAt: '2026-03-10T12:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T12:00:00Z' },
  { id: '12', name: 'Scaling Agent', cluster: ClusterType.INFRASTRUCTURE, status: AgentStatus.IDLE, config: {}, capabilities: ['scale', 'monitor'], tenantId: 't1', version: '1.2.0', description: 'Auto-scaling infrastructure', isEnabled: true, lastExecutionAt: '2026-03-10T06:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T06:00:00Z' },
  { id: '13', name: 'Finance Agent', cluster: ClusterType.BUSINESS, status: AgentStatus.IDLE, config: {}, capabilities: ['report', 'forecast'], tenantId: 't1', version: '1.0.0', description: 'Financial reporting and forecasting', isEnabled: true, lastExecutionAt: '2026-03-09T20:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-09T20:00:00Z' },
  // Phase 2 agents
  { id: '14', name: 'LLM Router Agent', cluster: ClusterType.LLM_INTELLIGENCE, status: AgentStatus.RUNNING, config: {}, capabilities: ['route', 'select-model', 'optimize'], tenantId: 't1', version: '1.0.0', description: 'Routes requests to optimal LLM models', isEnabled: true, lastExecutionAt: '2026-03-10T12:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T12:00:00Z' },
  { id: '15', name: 'Smart Orchestrator', cluster: ClusterType.INTELLIGENT_ORCHESTRATION, status: AgentStatus.RUNNING, config: {}, capabilities: ['plan', 'decompose', 'schedule'], tenantId: 't1', version: '1.0.0', description: 'Intelligent task decomposition and scheduling', isEnabled: true, lastExecutionAt: '2026-03-10T11:30:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T11:30:00Z' },
  { id: '16', name: 'Watchdog Monitor', cluster: ClusterType.WATCHDOG, status: AgentStatus.RUNNING, config: {}, capabilities: ['monitor', 'alert', 'diagnose'], tenantId: 't1', version: '1.0.0', description: 'System health monitoring and anomaly detection', isEnabled: true, lastExecutionAt: '2026-03-10T12:30:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T12:30:00Z' },
  { id: '17', name: 'Self-Evolution Engine', cluster: ClusterType.SELF_EVOLUTION, status: AgentStatus.IDLE, config: {}, capabilities: ['learn', 'adapt', 'improve'], tenantId: 't1', version: '1.0.0', description: 'Self-improving agent capabilities', isEnabled: true, lastExecutionAt: '2026-03-10T06:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-10T06:00:00Z' },
  { id: '18', name: 'Certification Agent', cluster: ClusterType.CERTIFICATION, status: AgentStatus.IDLE, config: {}, capabilities: ['audit', 'certify', 'validate'], tenantId: 't1', version: '1.0.0', description: 'Quality assurance and certification', isEnabled: true, lastExecutionAt: '2026-03-09T22:00:00Z', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-09T22:00:00Z' },
];

export const mockClusterStats: ClusterStats[] = Object.values(ClusterType).map((cluster) => {
  const agents = mockAgents.filter((a) => a.cluster === cluster);
  return {
    cluster,
    totalAgents: agents.length || Math.floor(Math.random() * 8) + 2,
    activeAgents: agents.filter((a) => a.status === AgentStatus.RUNNING).length || Math.floor(Math.random() * 4),
    idleAgents: agents.filter((a) => a.status === AgentStatus.IDLE).length || Math.floor(Math.random() * 3),
    errorAgents: agents.filter((a) => a.status === AgentStatus.ERROR).length || Math.floor(Math.random() * 1),
    agents,
  };
});

export const mockTasks: Task[] = [
  { id: 't1', type: 'web_scrape', agentId: '2', tenantId: 't1', status: TaskStatus.COMPLETED, priority: 7, input: { url: 'https://example.com' }, output: { data: 'scraped_content' }, error: null, retryCount: 0, maxRetries: 3, parentTaskId: null, scheduledAt: null, startedAt: '2026-03-10T10:00:00Z', completedAt: '2026-03-10T10:02:00Z', createdAt: '2026-03-10T09:55:00Z', updatedAt: '2026-03-10T10:02:00Z' },
  { id: 't2', type: 'code_review', agentId: '6', tenantId: 't1', status: TaskStatus.RUNNING, priority: 5, input: { repository: 'backend', pr: 42 }, output: null, error: null, retryCount: 0, maxRetries: 3, parentTaskId: null, scheduledAt: null, startedAt: '2026-03-10T11:00:00Z', completedAt: null, createdAt: '2026-03-10T10:55:00Z', updatedAt: '2026-03-10T11:00:00Z' },
  { id: 't3', type: 'threat_scan', agentId: '10', tenantId: 't1', status: TaskStatus.RUNNING, priority: 9, input: { scope: 'full' }, output: null, error: null, retryCount: 0, maxRetries: 3, parentTaskId: null, scheduledAt: null, startedAt: '2026-03-10T12:00:00Z', completedAt: null, createdAt: '2026-03-10T11:58:00Z', updatedAt: '2026-03-10T12:00:00Z' },
  { id: 't4', type: 'seo_analysis', agentId: '9', tenantId: 't1', status: TaskStatus.QUEUED, priority: 3, input: { domain: 'example.com' }, output: null, error: null, retryCount: 0, maxRetries: 3, parentTaskId: null, scheduledAt: '2026-03-10T14:00:00Z', startedAt: null, completedAt: null, createdAt: '2026-03-10T12:30:00Z', updatedAt: '2026-03-10T12:30:00Z' },
  { id: 't5', type: 'process_monitor', agentId: '4', tenantId: 't1', status: TaskStatus.FAILED, priority: 8, input: { pid: 1234 }, output: null, error: 'Process not found', retryCount: 3, maxRetries: 3, parentTaskId: null, scheduledAt: null, startedAt: '2026-03-10T08:00:00Z', completedAt: '2026-03-10T08:01:00Z', createdAt: '2026-03-10T07:55:00Z', updatedAt: '2026-03-10T08:01:00Z' },
  { id: 't6', type: 'terminal_exec', agentId: '3', tenantId: 't1', status: TaskStatus.COMPLETED, priority: 5, input: { command: 'ls -la' }, output: { stdout: 'drwxr-xr-x ...' }, error: null, retryCount: 0, maxRetries: 3, parentTaskId: null, scheduledAt: null, startedAt: '2026-03-10T12:00:00Z', completedAt: '2026-03-10T12:00:05Z', createdAt: '2026-03-10T11:59:00Z', updatedAt: '2026-03-10T12:00:05Z' },
  { id: 't7', type: 'document_create', agentId: '7', tenantId: 't1', status: TaskStatus.COMPLETED, priority: 4, input: { template: 'report' }, output: { fileId: 'doc_123' }, error: null, retryCount: 0, maxRetries: 3, parentTaskId: null, scheduledAt: null, startedAt: '2026-03-10T07:00:00Z', completedAt: '2026-03-10T07:05:00Z', createdAt: '2026-03-10T06:55:00Z', updatedAt: '2026-03-10T07:05:00Z' },
  { id: 't8', type: 'deploy', agentId: '12', tenantId: 't1', status: TaskStatus.PENDING, priority: 6, input: { env: 'production' }, output: null, error: null, retryCount: 0, maxRetries: 3, parentTaskId: null, scheduledAt: '2026-03-10T16:00:00Z', startedAt: null, completedAt: null, createdAt: '2026-03-10T12:45:00Z', updatedAt: '2026-03-10T12:45:00Z' },
  { id: 't9', type: 'security_audit', agentId: '10', tenantId: 't1', status: TaskStatus.RETRYING, priority: 9, input: { scope: 'infrastructure' }, output: null, error: 'Connection timeout', retryCount: 1, maxRetries: 3, parentTaskId: null, scheduledAt: null, startedAt: '2026-03-10T11:30:00Z', completedAt: null, createdAt: '2026-03-10T11:25:00Z', updatedAt: '2026-03-10T11:45:00Z' },
];

export const mockEvents: Event[] = [
  { id: 'e1', type: 'agent.started', namespace: 'agent.lifecycle', payload: { agentId: '1', agentName: 'Navigation Agent' }, source: 'agent-registry', severity: EventSeverity.INFO, tenantId: 't1', metadata: {}, createdAt: '2026-03-10T12:30:00Z' },
  { id: 'e2', type: 'task.failed', namespace: 'task.execution', payload: { taskId: 't5', error: 'Process not found' }, source: 'task-service', severity: EventSeverity.ERROR, tenantId: 't1', metadata: {}, createdAt: '2026-03-10T12:25:00Z' },
  { id: 'e3', type: 'agent.error', namespace: 'agent.lifecycle', payload: { agentId: '4', error: 'Unexpected shutdown' }, source: 'process-monitor', severity: EventSeverity.CRITICAL, tenantId: 't1', metadata: {}, createdAt: '2026-03-10T12:20:00Z' },
  { id: 'e4', type: 'cluster.scaled', namespace: 'infrastructure', payload: { cluster: 'browser', from: 3, to: 5 }, source: 'scaling-agent', severity: EventSeverity.INFO, tenantId: 't1', metadata: {}, createdAt: '2026-03-10T12:15:00Z' },
  { id: 'e5', type: 'security.alert', namespace: 'security', payload: { threat: 'suspicious_login', ip: '192.168.1.100' }, source: 'threat-detection', severity: EventSeverity.WARNING, tenantId: 't1', metadata: {}, createdAt: '2026-03-10T12:10:00Z' },
  { id: 'e6', type: 'task.completed', namespace: 'task.execution', payload: { taskId: 't1', duration: '2m' }, source: 'task-service', severity: EventSeverity.INFO, tenantId: 't1', metadata: {}, createdAt: '2026-03-10T12:05:00Z' },
  { id: 'e7', type: 'agent.registered', namespace: 'agent.registry', payload: { agentId: '14', name: 'New Agent' }, source: 'agent-registry', severity: EventSeverity.INFO, tenantId: 't1', metadata: {}, createdAt: '2026-03-10T12:00:00Z' },
  { id: 'e8', type: 'system.health', namespace: 'system', payload: { cpu: '45%', memory: '62%' }, source: 'health-monitor', severity: EventSeverity.INFO, tenantId: null, metadata: {}, createdAt: '2026-03-10T11:55:00Z' },
  { id: 'e9', type: 'security.breach', namespace: 'security', payload: { type: 'unauthorized_access', resource: 'admin-panel' }, source: 'access-control', severity: EventSeverity.CRITICAL, tenantId: 't1', metadata: {}, createdAt: '2026-03-10T11:50:00Z' },
  { id: 'e10', type: 'task.retrying', namespace: 'task.execution', payload: { taskId: 't9', attempt: 2 }, source: 'task-service', severity: EventSeverity.WARNING, tenantId: 't1', metadata: {}, createdAt: '2026-03-10T11:45:00Z' },
];

export const mockMissions: Mission[] = [
  {
    id: 'm1',
    name: 'Deploy Authentication Microservice',
    description: 'Build and deploy the new authentication microservice with OAuth2 support, including unit tests, integration tests, and security audit.',
    state: MissionState.BUILDING,
    priority: MissionPriority.HIGH,
    progress: 45,
    objectives: [
      { id: 'o1', description: 'Design API schema', completed: true },
      { id: 'o2', description: 'Implement OAuth2 flow', completed: true },
      { id: 'o3', description: 'Write unit tests', completed: false },
      { id: 'o4', description: 'Security audit', completed: false },
    ],
    constraints: ['Must be backward compatible', 'No PII in logs'],
    requiredCapabilities: ['coding', 'security', 'testing'],
    result: null,
    error: null,
    startedAt: '2026-03-10T08:00:00Z',
    completedAt: null,
    deadline: '2026-03-15T00:00:00Z',
    createdAt: '2026-03-09T14:00:00Z',
    updatedAt: '2026-03-10T12:00:00Z',
  },
  {
    id: 'm2',
    name: 'Marketing Campaign Q2',
    description: 'Create and launch the Q2 marketing campaign across all digital channels with A/B testing.',
    state: MissionState.TESTING,
    priority: MissionPriority.MEDIUM,
    progress: 72,
    objectives: [
      { id: 'o5', description: 'Design creative assets', completed: true },
      { id: 'o6', description: 'Set up A/B variants', completed: true },
      { id: 'o7', description: 'A/B test analysis', completed: false },
    ],
    constraints: ['Budget under $50k', 'Brand guidelines compliance'],
    requiredCapabilities: ['marketing', 'analytics'],
    result: null,
    error: null,
    startedAt: '2026-03-08T09:00:00Z',
    completedAt: null,
    deadline: '2026-03-20T00:00:00Z',
    createdAt: '2026-03-07T10:00:00Z',
    updatedAt: '2026-03-10T11:00:00Z',
  },
  {
    id: 'm3',
    name: 'Infrastructure Migration to K8s',
    description: 'Migrate all services from Docker Compose to Kubernetes with zero downtime.',
    state: MissionState.PLANNED,
    priority: MissionPriority.CRITICAL,
    progress: 10,
    objectives: [
      { id: 'o8', description: 'Assess current infrastructure', completed: true },
      { id: 'o9', description: 'Design K8s architecture', completed: false },
      { id: 'o10', description: 'Create Helm charts', completed: false },
      { id: 'o11', description: 'Migrate services', completed: false },
      { id: 'o12', description: 'Validate and certify', completed: false },
    ],
    constraints: ['Zero downtime', 'Rollback plan required'],
    requiredCapabilities: ['infrastructure', 'security', 'certification'],
    result: null,
    error: null,
    startedAt: null,
    completedAt: null,
    deadline: '2026-04-01T00:00:00Z',
    createdAt: '2026-03-10T08:00:00Z',
    updatedAt: '2026-03-10T08:00:00Z',
  },
  {
    id: 'm4',
    name: 'Security Compliance Audit',
    description: 'Perform comprehensive security audit and achieve SOC2 compliance certification.',
    state: MissionState.AUDITING,
    priority: MissionPriority.HIGH,
    progress: 60,
    objectives: [
      { id: 'o13', description: 'Vulnerability scan', completed: true },
      { id: 'o14', description: 'Penetration testing', completed: true },
      { id: 'o15', description: 'Remediation plan', completed: false },
      { id: 'o16', description: 'Compliance documentation', completed: false },
    ],
    constraints: ['Must follow NIST framework', 'External auditor review'],
    requiredCapabilities: ['security', 'certification'],
    result: null,
    error: null,
    startedAt: '2026-03-05T09:00:00Z',
    completedAt: null,
    deadline: '2026-03-25T00:00:00Z',
    createdAt: '2026-03-04T14:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'm5',
    name: 'Website Redesign',
    description: 'Complete redesign of the company website with improved UX and performance.',
    state: MissionState.COMPLETED,
    priority: MissionPriority.MEDIUM,
    progress: 100,
    objectives: [
      { id: 'o17', description: 'Design mockups', completed: true },
      { id: 'o18', description: 'Frontend implementation', completed: true },
      { id: 'o19', description: 'Performance optimization', completed: true },
      { id: 'o20', description: 'QA testing', completed: true },
    ],
    constraints: ['Mobile-first design', 'Core Web Vitals > 90'],
    requiredCapabilities: ['coding', 'browser', 'marketing'],
    result: { url: 'https://example.com', performanceScore: 95 },
    error: null,
    startedAt: '2026-02-15T09:00:00Z',
    completedAt: '2026-03-01T16:00:00Z',
    deadline: '2026-03-05T00:00:00Z',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-03-01T16:00:00Z',
  },
  {
    id: 'm6',
    name: 'Data Pipeline Optimization',
    description: 'Optimize the ETL data pipeline to reduce processing time by 50%.',
    state: MissionState.FAILED,
    priority: MissionPriority.HIGH,
    progress: 35,
    objectives: [
      { id: 'o21', description: 'Profile current pipeline', completed: true },
      { id: 'o22', description: 'Optimize transformations', completed: false },
      { id: 'o23', description: 'Scale infrastructure', completed: false },
    ],
    constraints: ['No data loss', 'Maintain ACID compliance'],
    requiredCapabilities: ['infrastructure', 'coding'],
    result: null,
    error: 'Pipeline timeout during stress test - unable to meet 50% reduction target',
    startedAt: '2026-03-06T08:00:00Z',
    completedAt: null,
    deadline: '2026-03-12T00:00:00Z',
    createdAt: '2026-03-05T09:00:00Z',
    updatedAt: '2026-03-09T14:00:00Z',
  },
  {
    id: 'm7',
    name: 'API Documentation Update',
    description: 'Update all API documentation to OpenAPI 3.1 spec with interactive examples.',
    state: MissionState.DRAFT,
    priority: MissionPriority.LOW,
    progress: 0,
    objectives: [
      { id: 'o24', description: 'Audit existing docs', completed: false },
      { id: 'o25', description: 'Write OpenAPI specs', completed: false },
      { id: 'o26', description: 'Add interactive examples', completed: false },
    ],
    constraints: ['Must cover all endpoints', 'Include error responses'],
    requiredCapabilities: ['coding', 'office'],
    result: null,
    error: null,
    startedAt: null,
    completedAt: null,
    deadline: null,
    createdAt: '2026-03-10T12:00:00Z',
    updatedAt: '2026-03-10T12:00:00Z',
  },
];

export const mockHealth = {
  status: 'ok' as const,
  info: {
    database: { status: 'up' },
    redis: { status: 'up', host: 'localhost', port: 6379, ping: 'PONG', version: '7.2.4', usedMemoryHuman: '1.23M', connectedClients: 5, keyCount: 128 },
    memory_heap: { status: 'up' },
    memory_rss: { status: 'up' },
    disk: { status: 'up' },
    agent_system: { status: 'up', agentRegistry: { initialized: true, registeredAgents: 18, lastSyncAt: '2026-03-10T12:30:00Z' }, queueSystem: { connected: true, pendingJobs: 3, activeWorkers: 5 } },
  },
  details: {
    database: { status: 'up' },
    redis: { status: 'up' },
    memory_heap: { status: 'up' },
    memory_rss: { status: 'up' },
    disk: { status: 'up' },
    agent_system: { status: 'up' },
  },
};

// Phase 8 — Orchestration Mock Data
export const mockClusterHealth: ClusterHealthInfo[] = Object.values(ClusterType).map((cluster, index) => {
  const statuses: ClusterHealthInfo['status'][] = ['healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'degraded', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'critical'];
  const status = statuses[index % statuses.length];
  const health = status === 'healthy' ? 90 + Math.floor(Math.random() * 10) : status === 'degraded' ? 50 + Math.floor(Math.random() * 30) : 10 + Math.floor(Math.random() * 25);
  const totalAgents = Math.floor(Math.random() * 8) + 2;
  const activeAgents = Math.floor(Math.random() * totalAgents);
  return {
    cluster,
    status,
    health,
    activeAgents,
    totalAgents,
    activeTasks: Math.floor(Math.random() * 12),
    completedTasks: Math.floor(Math.random() * 50) + 10,
    failedTasks: Math.floor(Math.random() * 3),
    avgResponseTime: Math.floor(Math.random() * 400) + 50,
    lastCheckedAt: '2026-03-10T12:30:00Z',
  };
});

export const mockConnectors: UnifiedConnectorInfo[] = [
  { id: 'c1', name: 'Web Scraper', type: 'browser', mode: 'active', status: 'connected', health: 98, capabilities: ['scrape', 'navigate', 'extract'], lastActivityAt: '2026-03-10T12:28:00Z', metadata: { version: '2.1.0' }, hitRate: 87, totalExecutions: 1243, successRate: 96 },
  { id: 'c2', name: 'Code Engine', type: 'coding', mode: 'active', status: 'connected', health: 95, capabilities: ['generate', 'review', 'refactor'], lastActivityAt: '2026-03-10T12:25:00Z', metadata: { version: '3.0.1' }, hitRate: 92, totalExecutions: 856, successRate: 94 },
  { id: 'c3', name: 'Terminal Bridge', type: 'computer', mode: 'active', status: 'connected', health: 91, capabilities: ['execute', 'shell', 'monitor'], lastActivityAt: '2026-03-10T12:30:00Z', metadata: { version: '1.5.0' }, hitRate: 78, totalExecutions: 2341, successRate: 89 },
  { id: 'c4', name: 'Doc Processor', type: 'office', mode: 'passive', status: 'connected', health: 88, capabilities: ['create', 'edit', 'convert'], lastActivityAt: '2026-03-10T12:15:00Z', metadata: { version: '1.2.0' }, hitRate: 65, totalExecutions: 432, successRate: 97 },
  { id: 'c5', name: 'Security Scanner', type: 'security', mode: 'hybrid', status: 'connected', health: 99, capabilities: ['scan', 'detect', 'alert'], lastActivityAt: '2026-03-10T12:29:00Z', metadata: { version: '2.3.0' }, hitRate: 71, totalExecutions: 3187, successRate: 99 },
  { id: 'c6', name: 'Infra Manager', type: 'infrastructure', mode: 'active', status: 'connected', health: 94, capabilities: ['deploy', 'scale', 'monitor'], lastActivityAt: '2026-03-10T12:20:00Z', metadata: { version: '1.8.0' }, hitRate: 55, totalExecutions: 678, successRate: 91 },
  { id: 'c7', name: 'Marketing Hub', type: 'marketing', mode: 'passive', status: 'disconnected', health: 0, capabilities: ['campaign', 'analytics', 'seo'], lastActivityAt: '2026-03-10T10:00:00Z', metadata: { version: '1.1.0' }, hitRate: 42, totalExecutions: 156, successRate: 88 },
  { id: 'c8', name: 'LLM Router', type: 'llm-intelligence', mode: 'hybrid', status: 'connected', health: 97, capabilities: ['route', 'select-model', 'optimize'], lastActivityAt: '2026-03-10T12:30:00Z', metadata: { version: '1.0.0' }, hitRate: 95, totalExecutions: 5621, successRate: 98 },
  { id: 'c9', name: 'Orchestrator Core', type: 'intelligent-orchestration', mode: 'active', status: 'connected', health: 96, capabilities: ['plan', 'decompose', 'schedule'], lastActivityAt: '2026-03-10T12:30:00Z', metadata: { version: '1.0.0' }, hitRate: 100, totalExecutions: 4523, successRate: 93 },
  { id: 'c10', name: 'Watchdog Sensor', type: 'watchdog', mode: 'hybrid', status: 'connected', health: 93, capabilities: ['monitor', 'alert', 'diagnose'], lastActivityAt: '2026-03-10T12:30:00Z', metadata: { version: '1.0.0' }, hitRate: 88, totalExecutions: 8934, successRate: 99 },
  { id: 'c11', name: 'Evolution Engine', type: 'self-evolution', mode: 'passive', status: 'initializing', health: 45, capabilities: ['learn', 'adapt', 'improve'], lastActivityAt: '2026-03-10T06:00:00Z', metadata: { version: '1.0.0' }, hitRate: 23, totalExecutions: 87, successRate: 76 },
  { id: 'c12', name: 'Certification Gate', type: 'certification', mode: 'passive', status: 'connected', health: 90, capabilities: ['audit', 'certify', 'validate'], lastActivityAt: '2026-03-10T09:00:00Z', metadata: { version: '1.0.0' }, hitRate: 34, totalExecutions: 213, successRate: 95 },
];

export const mockOrchestrationStats: OrchestrationStatistics = {
  totalCollaborations: 847,
  activeCollaborations: 12,
  totalDecompositions: 324,
  totalCoordinations: 1205,
  avgDecompositionTime: 1450,
  avgCoordinationTime: 890,
  connectorStats: mockConnectors.map((c) => ({
    connectorId: c.id,
    connectorName: c.name,
    hitRate: c.hitRate,
    totalExecutions: c.totalExecutions,
    successRate: c.successRate,
    avgResponseTime: Math.floor(Math.random() * 300) + 50,
  })),
  patternUsage: {
    delegation: 234,
    handoff: 156,
    parallel: 198,
    pipeline: 312,
    consensus: 89,
    swarm: 67,
  },
};

export const mockOrchestrationHistory: OrchestrationHistoryItem[] = [
  { id: 'oh1', type: 'collaboration', description: 'Deploy microservice with full CI/CD pipeline', status: 'completed', pattern: 'pipeline' as CollaborationPattern, createdAt: '2026-03-10T11:00:00Z', completedAt: '2026-03-10T11:45:00Z' },
  { id: 'oh2', type: 'decomposition', description: 'Break down Q2 marketing campaign into sub-tasks', status: 'completed', createdAt: '2026-03-10T10:30:00Z', completedAt: '2026-03-10T10:32:00Z' },
  { id: 'oh3', type: 'coordination', description: 'Coordinate security audit across 4 clusters', status: 'running', createdAt: '2026-03-10T12:00:00Z', completedAt: null },
  { id: 'oh4', type: 'collaboration', description: 'Parallel code review and testing', status: 'completed', pattern: 'parallel' as CollaborationPattern, createdAt: '2026-03-10T09:00:00Z', completedAt: '2026-03-10T09:30:00Z' },
  { id: 'oh5', type: 'decomposition', description: 'Decompose infrastructure migration plan', status: 'completed', createdAt: '2026-03-10T08:00:00Z', completedAt: '2026-03-10T08:05:00Z' },
  { id: 'oh6', type: 'collaboration', description: 'Swarm-based threat analysis', status: 'failed', pattern: 'swarm' as CollaborationPattern, createdAt: '2026-03-10T07:00:00Z', completedAt: '2026-03-10T07:12:00Z' },
  { id: 'oh7', type: 'coordination', description: 'Multi-agent document generation', status: 'completed', createdAt: '2026-03-09T16:00:00Z', completedAt: '2026-03-09T16:20:00Z' },
  { id: 'oh8', type: 'collaboration', description: 'Consensus-based architecture decision', status: 'running', pattern: 'consensus' as CollaborationPattern, createdAt: '2026-03-10T12:15:00Z', completedAt: null },
];

export const mockDecompositionResult: DecompositionResult = {
  id: 'dec1',
  missionId: 'm1',
  description: 'Deploy Authentication Microservice',
  objectives: ['Design API schema', 'Implement OAuth2 flow', 'Write unit tests', 'Security audit'],
  subTasks: [
    { id: 'st1', title: 'Design API Schema', description: 'Create OpenAPI 3.1 spec for authentication endpoints', cluster: ClusterType.CODING, priority: MissionPriority.HIGH, dependencies: [], estimatedEffort: '4h', status: 'completed' },
    { id: 'st2', title: 'Implement OAuth2 Flow', description: 'Build OAuth2 authorization code flow with PKCE', cluster: ClusterType.CODING, priority: MissionPriority.HIGH, dependencies: ['st1'], estimatedEffort: '8h', status: 'running' },
    { id: 'st3', title: 'Security Review', description: 'Review OAuth2 implementation for security vulnerabilities', cluster: ClusterType.SECURITY, priority: MissionPriority.CRITICAL, dependencies: ['st2'], estimatedEffort: '3h', status: 'pending' },
    { id: 'st4', title: 'Write Unit Tests', description: 'Cover all authentication endpoints with 90%+ coverage', cluster: ClusterType.CODING, priority: MissionPriority.HIGH, dependencies: ['st2'], estimatedEffort: '6h', status: 'pending' },
    { id: 'st5', title: 'Deploy to Staging', description: 'Deploy service to staging environment for integration testing', cluster: ClusterType.INFRASTRUCTURE, priority: MissionPriority.MEDIUM, dependencies: ['st3', 'st4'], estimatedEffort: '2h', status: 'pending' },
    { id: 'st6', title: 'Generate Documentation', description: 'Create API documentation and integration guide', cluster: ClusterType.OFFICE, priority: MissionPriority.LOW, dependencies: ['st1'], estimatedEffort: '3h', status: 'pending' },
  ],
  strategy: 'dependency-first',
  estimatedDuration: '26h',
  createdAt: '2026-03-10T12:00:00Z',
};

export const mockCollaborationResult: CollaborationResult = {
  id: 'col1',
  pattern: 'pipeline',
  description: 'Deploy microservice with full CI/CD pipeline',
  objectives: ['Build', 'Test', 'Security Scan', 'Deploy'],
  status: 'running',
  participants: ['c2', 'c5', 'c6'],
  result: null,
  error: null,
  startedAt: '2026-03-10T12:00:00Z',
  completedAt: null,
  createdAt: '2026-03-10T12:00:00Z',
  updatedAt: '2026-03-10T12:15:00Z',
};

export const mockCoordinationResult: CoordinationResult = {
  id: 'cor1',
  taskIds: ['st1', 'st2', 'st3', 'st4', 'st5', 'st6'],
  strategy: 'dependency-graph',
  status: 'coordinating',
  assignments: [
    { taskId: 'st1', agentId: '5', cluster: ClusterType.CODING, scheduledAt: '2026-03-10T12:00:00Z', startedAt: '2026-03-10T12:00:00Z', completedAt: '2026-03-10T12:30:00Z', status: 'completed' },
    { taskId: 'st2', agentId: '6', cluster: ClusterType.CODING, scheduledAt: '2026-03-10T12:30:00Z', startedAt: '2026-03-10T12:30:00Z', completedAt: null, status: 'running' },
    { taskId: 'st3', agentId: '10', cluster: ClusterType.SECURITY, scheduledAt: '2026-03-10T14:30:00Z', startedAt: null, completedAt: null, status: 'pending' },
    { taskId: 'st4', agentId: '5', cluster: ClusterType.CODING, scheduledAt: '2026-03-10T14:30:00Z', startedAt: null, completedAt: null, status: 'pending' },
    { taskId: 'st5', agentId: '12', cluster: ClusterType.INFRASTRUCTURE, scheduledAt: '2026-03-10T17:30:00Z', startedAt: null, completedAt: null, status: 'pending' },
    { taskId: 'st6', agentId: '7', cluster: ClusterType.OFFICE, scheduledAt: '2026-03-10T13:00:00Z', startedAt: null, completedAt: null, status: 'pending' },
  ],
  timeline: {
    phases: [
      { name: 'Design & Schema', taskIds: ['st1', 'st6'], startAfter: null, estimatedDuration: '4h' },
      { name: 'Core Implementation', taskIds: ['st2', 'st4'], startAfter: 'st1', estimatedDuration: '14h' },
      { name: 'Security & Validation', taskIds: ['st3'], startAfter: 'st2', estimatedDuration: '3h' },
      { name: 'Deployment', taskIds: ['st5'], startAfter: 'st3,st4', estimatedDuration: '2h' },
    ],
    estimatedTotalDuration: '23h',
  },
  result: null,
  error: null,
  createdAt: '2026-03-10T12:00:00Z',
  updatedAt: '2026-03-10T12:15:00Z',
};
